#created on: Mar 27, 2012
package org.acme.insurance.pricing

#list any import classes here.
import org.acme.insurance.Driver
import org.acme.insurance.Policy

rule "safeyouths"

    when
        #conditions
        driver : Driver(age > 17 && < 25, numberOfAccidents < 1, numberOfTickets <= 1)
		policy : Policy(price == 0, policyType == "AUTO")
    then
        #actions
        modify(policy) {setPrice(450)}
        System.out.println("fired rule " + kcontext.getRule().getName());

end

