package org.acme.insurance.pricing
	
rule "PriceMultipleVehicles"

	salience -10

    when
        adriver: Driver()
        pMaster: Policy(driver==adriver,policyType=="MASTER",price==0)
        totalPrice: Number( intValue > 0 )
        	from accumulate( Policy(driver==adriver,policyType=="AUTO", priceVal:price),
        	sum(priceVal))
    then
        #actions
        modify(pMaster) {setPrice(totalPrice.intValue())}
        System.out.println("fired rule " + kcontext.getRule().getName());
end
